### ISSUE TITLE
Describe what 'civic tech' is

### ISSUE THREAD

**Issue by mheadd** [mheadd/how-to-talk-to-civic-hackers#1]
Add a summary description and/or point to other sources that have defined what civic tech is and reference in Section 1, and other places where the term is used.

**Comment by JBStephens1** [comment]
If this is still a concern, I'd be glad to share my review of civic tech definitions. I lean more toward the "free volunteers" components which make it "civic" - but recognize a range of views about the role of for-profits in civic tech.
