### ISSUE TITLE
ePub and Kindle

### ISSUE THREAD

**Issue by sillygwailo** [mheadd/how-to-talk-to-civic-hackers#7]
Would it be possible to include an ePub and Kindle version of the book so we can read it on our e-reader?

**Comment by mheadd** [comment]
@sillygwailo If you go to the [details page](https://www.gitbook.com/book/mheadd/how-to-talk-to-civic-hackers/details), you can download the book in different formats.

![screen shot 2016-10-27 at 7 17 44 pm](https://cloud.githubusercontent.com/assets/58419/19789001/1755dc44-9c7a-11e6-9477-e8a050619642.png)
